Numpy를 사용한 코드가 순수 파이썬으로 작성한 코드보다 열배에서 백 배 이상 빠르고 메모리도 더 적게 사용하는 것을 확인할 수 있다.

In [3]:
import numpy as np
a=[1,2,3] #리스트
b=np.array(a) # 배열
c=a
d=b
b[0]=5
print(a)
c[0]=5
print(a)
d[0]=6
print(a)
print(b)

[1, 2, 3]
[5, 2, 3]
[5, 2, 3]
[6 2 3]


In [236]:
import numpy as np
dir(np)

## 1. 1차원 배열

In [237]:
#파이썬의리스트
#다양한 자료형 가능
a= [1,2,3,'a','b']
print(a)
print(type(a))

[1, 2, 3, 'a', 'b']
<class 'list'>


In [238]:
#배열
a= np.array([1,2,3,'a','b'])
print(a)
#동일한 자료형만 가능해서 모두 문자형으로 바뀜
print(type(a))  #n-dimension array
print(a.shape)  #구조
print(a.ndim)   #차원
print(a.dtype)  #자료형

['1' '2' '3' 'a' 'b']
<class 'numpy.ndarray'>
(5,)
1
<U11


In [239]:
a= np.array([1,2,3,'4','5'],dtype=float) # 전체 데이터를 실수형으로
print(a)
print(a.dtype)

[1. 2. 3. 4. 5.]
float64


### (1) 벡터화 연산
    벡터: 1차원 배열
    행렬(metrix): 2차원 배열
    
    리스트의 연산자는 진짜 연산(계산)이 아님
    
    

In [240]:
a=[1,2,3,4,5]
b= np.array(a)
print(a*2)
print(b*2)
print(b-5)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[-4 -3 -2 -1  0]


### (2) 인덱스 접근
    변수가 메모리에 연속적으로 존재

In [241]:
print(b[0],b[1])

1 2


## 2. 2차원 배열

In [242]:
a=np.array([[1,2,3],[4,5,6]])

print(a)
print(a.shape)  #2행 3열
print(a.ndim)   #2차원
print(a.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


### 인덱스 접근

In [243]:
print(a)
print(a[0])
print(a[0][1])     # 중첩리스트도 가능
print(a[0,0]) # [행,열], 이건 리스트에서 안됨

print(len(a))
print(len(a[0]))

[[1 2 3]
 [4 5 6]]
[1 2 3]
2
1
2
3


## 3. 3차원 배열

In [244]:
a= np.array([[[1,2,3,4],[5,6,7,8]],[[2,3,4,5],[6,7,8,9]]])
print(a)
print(a.shape)   #2면 2줄 4개
print(a.ndim)    #3차원

print(len(a))
print(len(a[0]))
print(len(a[0][0]))

[[[1 2 3 4]
  [5 6 7 8]]

 [[2 3 4 5]
  [6 7 8 9]]]
(2, 2, 4)
3
2
2
4


## 4.집계함수

In [245]:
x=np.random.rand(8)
print(x)

y=np.random.rand(8)
print(y)

[0.06566367 0.04350119 0.39515076 0.66842705 0.19802711 0.87626645
 0.4323891  0.61964146]
[0.29042674 0.61525457 0.95365996 0.44801472 0.20704984 0.42536729
 0.44457426 0.50761749]


In [246]:
np.maximum(x,y)  #같은 위치의 x,y값을 비교해서 큰값

array([0.29042674, 0.61525457, 0.95365996, 0.66842705, 0.20704984,
       0.87626645, 0.44457426, 0.61964146])

In [247]:
#      ?np.random.rand로 도움말 보기
arr= np.random.rand(5,4)  #5행 4열로 난수 생성
print(arr)

[[0.52573325 0.04242919 0.16441909 0.45022718]
 [0.70797117 0.77758791 0.777103   0.50277875]
 [0.95674759 0.33187371 0.48145816 0.748374  ]
 [0.85783952 0.41446006 0.84868451 0.44457094]
 [0.71574708 0.00844836 0.02520142 0.94045049]]


In [248]:
print(arr.sum()) #전체 합계
print(arr.sum(axis=0))  # 열의 합
print(arr.sum(axis=1))  # 행의 합

10.722105400586981
[3.76403862 1.57479923 2.29686619 3.08640137]
[1.18280871 2.76544083 2.51845347 2.56555503 1.68984737]


## 5. 배열의 인덱싱

In [249]:
arr= np.array([0,1,2,3,4])
print(arr[-1]) #역순 접근 가능

4


In [1]:
import numpy as np
arr= np.array([i for i in range(10)])

idx= np.array([True, False,True,False,True, False,True, False,True, False])
print(arr[idx])       #배열에서 인덱스를 조건문으로 접근가능
print(arr[arr%2==0])    # fancy indexing
print(arr[arr%3==0])
print(arr[arr%4==1])
print(arr[(arr%3==0)&(arr%4==1)])    # 논리연산자 and  비트연산자 &

[0 2 4 6 8]
[0 2 4 6 8]
[0 3 6 9]
[1 5 9]
[9]


In [3]:
#(arr<10) and (arr>2)   # 논리연산자는 여러개를 동시에 계산 못함. 
# 비트연산자는 이진수로 바꿔서 계산

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 6.배열의 슬라이싱

In [296]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,0,11]])
print(arr)
print(arr[0, 0:2])   #[인덱스, 슬라이싱]
print(arr[1:3, 0:2])
print(arr[0, :])
print(arr[[2,1,0],:])    # 2,1,0 인덱스 순서로
print(arr[:,[1,2,3]])  #[슬라이싱, 인덱스]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9  0 11]]
[0 1]
[[4 5]
 [8 9]]
[0 1 2 3]
[[ 8  9  0 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9  0 11]]


## 7. numpy 자료형
    b: boolean
    i: 정수형 32bit= 4byte
    u: 부호 없는 정수형. 0,양수
    f: 부동 소수점
    c: 복소수
    O: 객체
    S: 바이트 문자열(ASCII) 1바이트(영어)
    U: 유니코드 문자열      2바이트(한글)

In [252]:
arr=np.array([1,2,3], dtype='f')
# arr=np.array([1,2,3], dtype=np.float16)
print(arr.dtype)


float32


In [253]:
arr=np.array([1,2,3], dtype='S')
print(arr[0]+arr[2]) # 문자로 바꼈음

b'13'


## 8. 배열 생성

In [254]:
print(np.zeros(5))
print(np.zeros(4,dtype='i8')) #64비트 정수
arr=np.zeros(5,dtype='U4') #유니코드로 4글자
arr[0]='abc'
arr[1]='cvddse'
arr[3]=2345667
print(arr)
print(np.zeros((2,3)))

[0. 0. 0. 0. 0.]
[0 0 0 0]
['abc' 'cvdd' '' '2345' '']
[[0. 0. 0.]
 [0. 0. 0.]]


In [255]:
arr=np.ones((2,3,4))      #단위행렬
print(arr)

arr=np.zeros((2,5))
print(arr)
print(np.ones_like(arr))  #0으로 구성된 행렬을 모두 1로 바꿈

arr= np.empty((4,3))   # 초기화되지않은. 원래 메모리에 있던 값
print(arr)

arr= np.arange(10)   #range를 array로
print(arr)

arr= np.linspace(0, 100, 5)   #0부터 100까지 5개로 나눠서
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[6.36598737e-314 6.36598737e-314 6.36598737e-314]
 [1.27319747e-313 1.48539705e-313 6.36598738e-314]
 [1.48539705e-313 1.27319747e-313 1.06099790e-313]
 [9.88131292e-324 4.24399159e-314 2.12199580e-314]]
[0 1 2 3 4 5 6 7 8 9]
[  0.  25.  50.  75. 100.]


## 9. 전치 연산(Transpose)


In [256]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 10. 배열의 크기 변경
배열의 연산은 크기가 같을 때만 사용 가능
- reshape()
- flatten()   #고차원-> 1차원
- ravel()

In [257]:
arr= np.arange(12)
print(arr.shape)
print(arr.ndim)

(12,)
1


In [258]:
arr1= arr.reshape(3,4)  #1차원을 3행 4열로
print(arr1)
print(arr1.shape)

arr2= arr.reshape(3,-1)  # 3행에 열은 자동 계산
print(arr2)

arr3= arr.reshape(-1,4)  # 4열에 행 자동 계산
print(arr3)

arr4= arr.reshape(2,2,3)  # 3차원으로 2면 2행 3열. -1로 자동계산가능
print(arr4)
print(arr4.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


In [259]:
print(arr4.reshape(12))  #다시 1차원으로
print(arr4.flatten())    #계산 필요 없이 바로 1차원으로
print(arr4.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


## 11. 배열의 연결(병합) 덧셈 아님
방향에따라 크기(개수), 차원이 같아야 가능하다
- hstack(), vstack()
- concatenate()
- dstack(), stack()
- tile(): 자기복제

### (1) hstack(), vstack()

In [260]:
#1차원 배열

a= np.random.randint(0, 10, (4,))    #0부터 10중에서 4개
print(a)

b= np.ones(4, dtype='i')
print(b)

print(np.vstack([a,b]))  # 수직으로 병합. 2차원으로 증가되는 효과
print(np.hstack([a,b]))  # 수평으로 병합. 그대로 1차원

[3 0 4 6]
[1 1 1 1]
[[3 0 4 6]
 [1 1 1 1]]
[3 0 4 6 1 1 1 1]


In [261]:
#2차원 배열. 차원 그대로 유지

a= np.random.randint(0, 10, (2,2))
b= np.random.randint(0, 10, (2,2))
print(a)
print(b)
print(np.vstack([a,b])) 
print(np.hstack([a,b]))

[[2 7]
 [9 3]]
[[1 1]
 [9 9]]
[[2 7]
 [9 3]
 [1 1]
 [9 9]]
[[2 7 1 1]
 [9 3 9 9]]


### (2) concatenate()
단순 합치기

In [262]:
# 1차원 배열

a= np.random.randint(0, 10, (4,))    #0부터 10중에서 4개
print(a)

b= np.ones(4, dtype='i')
print(b)

print(np.concatenate([a,b]))    # hstack()과 비슷
print('============')

#2차원 배열. 차원 그대로 유지

a= np.random.randint(0, 10, (1,4))
b= np.random.randint(0, 10, (1,4))
print(a)
print(b)
print(np.concatenate([a,b], axis=0))  # 수직으로(1축)
print(np.concatenate([a,b], axis=1))  # axis 축. default=0 수평으로.
# print(np.hstack([a,b]))
print('============')

a= np.random.randint(0, 10, (3,4))
b= np.random.randint(0, 10, (3,2))
print(a)
print(b)
# print(np.concatenate([a,b], axis=0))  # 사이즈가 맞아야함
print(np.concatenate([a,b], axis=1))  # axis 축. default=0 수평으로.
# print(np.hstack([a,b]))

[0 8 0 8]
[1 1 1 1]
[0 8 0 8 1 1 1 1]
[[5 3 5 8]]
[[3 6 1 6]]
[[5 3 5 8]
 [3 6 1 6]]
[[5 3 5 8 3 6 1 6]]
[[1 2 1 2]
 [6 6 1 3]
 [3 2 3 2]]
[[3 3]
 [0 5]
 [1 2]]
[[1 2 1 2 3 3]
 [6 6 1 3 0 5]
 [3 2 3 2 1 2]]


In [263]:
a= np.random.randint(0,10,(4,2,3))
b= np.random.randint(0,10,(5,2,3))
print(a)  
print(b)
print('============')

c=np.concatenate([a,b], axis=0)     # shape을 기준으로 서로 다른 위치일때 axis 가능. axis=-1은 마지막 차원..? 차원축소...?
# print(c)
print(c.shape)   # (9,2,3)

[[[1 6 2]
  [1 3 6]]

 [[3 9 0]
  [4 2 7]]

 [[5 5 3]
  [9 1 8]]

 [[1 4 6]
  [2 6 7]]]
[[[5 0 1]
  [5 6 9]]

 [[8 8 2]
  [6 0 6]]

 [[0 4 3]
  [3 7 0]]

 [[9 2 2]
  [3 5 6]]

 [[0 6 0]
  [3 7 3]]]
(9, 2, 3)


### (3) stack(), dstack()
    행과 열을 뽑아서 합친다?
    값을 더하는건 아님
~합친 결과는 항상 3차원~

    dstack은 열을 합침. 3차원


np.ones((shape),dtype)

In [264]:
a1= np.ones((3,4))    
a2= np.zeros((3,4))
print(a1,'\n', a2)
print('============')

a3= np.stack([a1,a2])  # 차원 증가
print(a3.shape)        # (2,3,4)
print(a3)
print('============')

a3= np.stack([a1,a2], axis=1)  # 행끼리 합침
print(a3.shape)                # (3,2,4)
print(a3)
print('============')

a3= np.stack([a1,a2], axis=2)  # 열끼리 합침 = dstack
print(a3.shape)                # (3,4,2)
print(a3)
print('============')

a3= np.dstack([a1,a2])
print(a3.shape)
print(a3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(2, 3, 4)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(3, 2, 4)
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]
(3, 4, 2)
[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
(3, 4, 2)
[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


In [265]:
a1= np.array([1,2,3])
a2= np.array([4,5,6])
a3= np.dstack([a1,a2])     # 열끼리 묶음
print(a3)
print(a3.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [266]:
a= np.random.randint(1,10,(100,200,3))
b= np.random.randint(1,10,(100,200,3))
c= np.random.randint(1,10,(100,200,3))
d= np.dstack([a,b,c])
print(d.shape)

(100, 200, 9)


In [267]:
e= np.stack([a,b,c],axis=1)
print(e.shape)  # 면이 증가

(100, 3, 200, 3)


### (4) tile()
- ?np.tile
- np.tile(A,resp)

In [268]:
a=1
b= np.array([0,1])
c= np.array([[0,1],[2,3]])
print(a)
print(b)
print(c)

1
[0 1]
[[0 1]
 [2 3]]


In [269]:
# resp가 상수일경우. 자기복제. 차원이 늘어나진 않음 .x3열

print(np.tile(a,3))
print(np.tile(b,3))
print(np.tile(c,3))

[1 1 1]
[0 1 0 1 0 1]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]]


In [270]:
# resp가 튜플일경우. 차원 지정. x3열 x2행

print(np.tile(a,{2,3}))
print(np.tile(b,{2,3}))
print(np.tile(c,{2,3}))

[[1 1 1]
 [1 1 1]]
[[0 1 0 1 0 1]
 [0 1 0 1 0 1]]
[[0 1 0 1 0 1]
 [2 3 2 3 2 3]
 [0 1 0 1 0 1]
 [2 3 2 3 2 3]]


## 12. Broadcasting
    차원이 달라도 계산됨
    길이가 1이거나 축의 기준이 같아야한다
    

In [271]:
a=np.array([1,2,3])
b=np.array([1])

print(a+b)

[2 3 4]


In [22]:
import numpy as np
y= np.arange(1,4)
print(y)
print(y.T)       # Transpose는 1차원에서는 안된다.
x= y[np.newaxis,:]  #축을 추가해서 차원변경?   
print(x)
x.shape

[1 2 3]
[1 2 3]
[[1 2 3]]


(1, 3)

In [4]:
x= np.vstack([range(8)[i:i+3] for i in range(5)])    #range(8)에서 슬라이싱
print(x)
y= np.arange(5)
print(y.T)
y= np.arange(5)[:, np.newaxis]  #축을 추가해서 차원변경?   Transpose는 1차원에서는 안된다.
print(y)

z= y.reshape(5,1)
print(z)

print(x+y)
# y=5는 연산 가능

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]


In [273]:
[range(10)[i:i+3] for i in range(5)]

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]

## 13. 차원축소(dimension reduction) 연산

    최대값/최소값: max(),min(),argmax(), argmin()  -> 값의 위치
    대표값: mean, sum, median, std, var
    논리값: all, any

In [274]:
x= np.array([2,9,6,8,4])
print(np.max(x))
print(np.argmax(x))
print(np.argmin(x))

9
1
0


## 14.기술 통계
    sum(), mean()
    max(), min()
    var(), std()
    len()
    median(): 중앙값, 중간값
    percentile(): 사분위수
    ...

In [275]:
import scipy.stats

x= np.random.randn(20)
print(x)

scipy.stats.describe(x)

[-9.45337951e-01  6.48389763e-01  2.12956670e-03 -1.24322585e-01
 -4.45892406e-01  2.20775058e+00  9.80132816e-01  3.49966777e-02
 -2.74022851e-01 -4.44406975e-01 -1.81888544e+00  4.93222501e-01
  1.13909616e+00 -1.24756657e+00  5.79261354e-01 -9.42684042e-01
  2.37004687e+00  1.71900471e-01  1.27842902e+00 -1.29500701e+00]


DescribeResult(nobs=20, minmax=(-1.8188854442891071, 2.3700468749338737), mean=0.11836149703659178, variance=1.26024561296712, skewness=0.3292718814638921, kurtosis=-0.46441815101957573)

## 15. 정렬
    원본 수정되지 않음

In [276]:
arr= np.array([[4,25,6,17],[28,35,12,4],[22,7,14,2,]])
print(np.sort(arr))     #행별로 정렬 axis=0
print(np.sort(arr, axis=0)) # 열별로 정렬

[[ 4  6 17 25]
 [ 4 12 28 35]
 [ 2  7 14 22]]
[[ 4  7  6  2]
 [22 25 12  4]
 [28 35 14 17]]


In [277]:
arr.sort()   #원본이 수정됨
print(arr)

[[ 4  6 17 25]
 [ 4 12 28 35]
 [ 2  7 14 22]]


In [278]:
#argsort()
arr= np.array([38,48,19,63])
idx= np.argsort(arr)  # 순서대로 인덱스생성
print(idx)
print(arr[idx])

[2 0 1 3]
[19 38 48 63]


In [279]:
# 내림차순. 슬라이싱 이용 간격-1

print(np.sort(arr)[::-1])
print(arr[np.argsort(-arr)])

[63 48 38 19]
[63 48 38 19]


In [280]:
# 슬라이싱: 배열[시작위치:끝위치+1: 간격]
ex= np.arange(10)
print(ex[:])
print(ex[::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


## 16. 난수
    rand(): 0~1 사이의 균일분포. 확률이 동일
    randn(): 정규분포
    randint(): 균일분포에서 정수

In [281]:
print(np.random.rand(3,4))   #3행 4열
print(np.random.randint(10)) #0~9 중 하나
print(np.random.randint(11,20, size=(2,3)))

[[0.0474068  0.0303776  0.27614696 0.95238884]
 [0.64191592 0.12410821 0.81293146 0.42005312]
 [0.57098367 0.29468024 0.56058369 0.99394561]]
7
[[14 12 16]
 [19 17 13]]


### (1) 재현성(난수 고정)

In [282]:
np.random.seed(2) # seed를 5로 고정
np.random.rand(2)

array([0.4359949 , 0.02592623])

### (2) 데이터의 순서 바꾸기

In [283]:
x= np.arange(10)
print(x)
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[9 5 4 7 1 8 0 3 2 6]


### (3) 샘플링: 복원(default), 비복원

In [284]:
print(np.random.choice(5,5)) #0부터 4까지 5개. 복원추출

[2 4 4 4 3]


In [285]:
print(np.random.choice(7,5, replace=False)) #비복원추출

[1 0 5 3 2]


In [286]:
print(np.random.choice(5,10,p=[0.1,0,0.3,0.6,0])) #확률 조정


[3 3 2 3 2 2 2 2 3 3]


## 17.정수형 데이터 카운팅
    unique()
    bincount()

### (1) unique()
    중복 제거

In [287]:
arr= np.array(['a','b','c','a','c'])

In [288]:
print(len(arr))
print(np.unique(arr))
idx, cnt= np.unique(arr, return_counts=True)
print(idx)
print(cnt)

5
['a' 'b' 'c']
['a' 'b' 'c']
[2 1 2]


### (2) bincount()
    발생하지 않은 사건에 대해서도 카운팅

In [290]:
arr= np.array([1,1,2,2,2,3,4])
print(np.unique(arr, return_counts=True)) #발생하지 않은건 카운트X
print(np.bincount(arr, minlength=6))

(array([1, 2, 3, 4]), array([2, 3, 1, 1], dtype=int64))
[0 2 3 1 1 0]


## 18. 실습 541p.