In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name= fm.FontProperties(fname='C:\\Windows\\Fonts\\malgun.ttf').get_name()
plt.rc('font',family=font_name)

import matplotlib as mlp
mlp.rcParams['axes.unicode_minus']=False

from bs4 import BeautifulSoup
import requests

In [21]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

In [3]:
driver= webdriver.Chrome('C:\\Users\\acorn\\Downloads\\chromedriver')
driver.get('https://parking.seoul.go.kr/#')

C:\Users\acorn\AppData\Local\Temp\ipykernel_10400\1506105961.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver= webdriver.Chrome('C:\\Users\\acorn\\Downloads\\chromedriver')


In [5]:
driver.find_element(By.CLASS_NAME, 'ico3 on')

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".ico3 on"}
  (Session info: chrome=111.0.5563.147)
Stacktrace:
Backtrace:
	(No symbol) [0x003CDCE3]
	(No symbol) [0x003639D1]
	(No symbol) [0x00274DA8]
	(No symbol) [0x002A019F]
	(No symbol) [0x002A03AB]
	(No symbol) [0x002CEE62]
	(No symbol) [0x002BAF14]
	(No symbol) [0x002CD57C]
	(No symbol) [0x002BACC6]
	(No symbol) [0x00296F68]
	(No symbol) [0x002980CD]
	GetHandleVerifier [0x00643832+2506274]
	GetHandleVerifier [0x00679794+2727300]
	GetHandleVerifier [0x0067E36C+2746716]
	GetHandleVerifier [0x00476690+617600]
	(No symbol) [0x0036C712]
	(No symbol) [0x00371FF8]
	(No symbol) [0x003720DB]
	(No symbol) [0x0037C63B]
	BaseThreadInitThunk [0x74EC00F9+25]
	RtlGetAppContainerNamedObjectPath [0x76F07BBE+286]
	RtlGetAppContainerNamedObjectPath [0x76F07B8E+238]


1. pandas, numpy, matplotlib
2. 
3. numpy의 배열은 1. 연산이 가능하다. 2. 메모리
4. [0-9], \d
5. 서로 다른 shape의 데이터를 병합하는 것이다.
6. 
7. 
8. 데이터의 종류를 알 수 있다. 
9. Series, DataFrame
10. 

In [13]:
import numpy as np
import pandas as pd

In [3]:
a = np.random.randint(0, 10, (100, 200, 5))
b = np.random.randint(0, 10, (100, 200, 2))

In [104]:
data = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12])

In [106]:
data.reshape(1,1,-1).ndim

3

In [28]:
#3
import MySQLdb
import sqlite3

conn = MySQLdb.connect(host="127.0.0.1", user="root", password="1111",  database="testdb")

cur=conn.cursor()
cur.execute('create table if not exists users(name varchar(10), age int, addr varchar(50))')
conn.commit()
cur.execute('insert into users values("홍길동", 20, "서울시 강남구")')
conn.commit()

conn.close()

In [31]:
conn= sqlite3.connect('data/auto.db')
cur= conn.cursor()
cur.execute('create table if not exists users(name varchar(10), age int, addr varchar(50))')
conn.commit()

cur.execute('insert into users values("홍길동", 20, "서울시 강남구")')
conn.commit()

cur.execute('select * from users')
for row in cur:
    print(row)
    
conn.close()

('홍길동', 20, '서울시 강남구')


In [ ]:
#4

In [45]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
b=a+2
b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
b.reshape(1,3,3)

array([[[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

In [85]:
#5
v=[4,5,6]

In [86]:
a= np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
np.vstack([a, v]).T

array([[0., 0., 4.],
       [0., 0., 5.],
       [0., 0., 6.]])

In [97]:
a = np.random.randint(0, 10, (100, 200, 5))
b = np.random.randint(0, 10, (100, 200, 2))
np.dstack([a,b]).shape

(100, 200, 7)

In [98]:
a= np.array([1,2,3,4,5,6])

In [102]:
a.reshape(1,2,3).ndim

3

In [109]:
import re
data='''py one
life is short
py two
you need py
py three
other py four'''
print(re.findall('^py [a-z]+',data))
print(re.findall('^py [a-z]+',data, re.M))
# print(p1.findall(p1,data))
# print(p2.findall('hi HI'))

['py one']
['py one', 'py two', 'py three']


In [115]:
data = """
<a href="abc1.html">abc1</a>
<a href="abc2.html">abc2</a>
<a href="abc3.html">abc3</a>
<a href="xyz.html">xyz</a>
<a href="pic.jpg">pic</a>
"""

In [123]:
re.findall('".*"',data, re.M)

['"abc1.html"', '"abc2.html"', '"abc3.html"', '"xyz.html"', '"pic.jpg"']

In [124]:
data = """
        <div class="select_div">
            <span data-i18n="footer.relationSites">연관사이트</span>
            <ul>
            </ul>
        </div>
        <ul class="list_sns">
            <li><a href="https://www.facebook.com/ekoreatech" target="_blank"><img src="/res/lms/img/common/btn_footer_sns1.png" alt="페이스북"></a></li>
            <li><a href="https://blog.naver.com/e-koreatech" target="_blank"><img src="/res/lms/img/common/btn_footer_sns2.png" alt="블로그"></a></li>
            <li><a href="https://www.youtube.com/user/koreatecholei" target="_blank"><img src="/res/lms/img/common/btn_footer_sns3.png" alt="유트브"></a></li>
        </ul>
"""

In [126]:
re.findall('https://.* target',data, re.M)

['https://www.facebook.com/ekoreatech" target',
 'https://blog.naver.com/e-koreatech" target',
 'https://www.youtube.com/user/koreatecholei" target']

In [153]:
df = pd.DataFrame(np.random.randint(10, size=(4, 8)))
df

0  1  2  3  4  5  6  7
0  2  3  6  9  9  1  6  9
1  9  1  1  7  3  1  2  3
2  7  7  0  3  8  7  6  6
3  3  5  3  7  9  7  6  0

In [154]:
df.sum(axis=1)

0    45
1    27
2    44
3    40
dtype: int64

In [155]:
df.append(df.sum(axis=0),ignore_index=True)

C:\Users\acorn\AppData\Local\Temp\ipykernel_38532\214213505.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(df.sum(axis=0),ignore_index=True)


0   1   2   3   4   5   6   7
0   2   3   6   9   9   1   6   9
1   9   1   1   7   3   1   2   3
2   7   7   0   3   8   7   6   6
3   3   5   3   7   9   7   6   0
4  21  16  10  26  29  16  20  18

In [157]:
df['행의합']= df.sum(axis=1)
df.append({'열의합':df.sum(axis=0)},ignore_index=True)

C:\Users\acorn\AppData\Local\Temp\ipykernel_38532\4055201129.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append({'열의합':df.sum(axis=0)},ignore_index=True)


0    1    2    3    4    5    6    7   행의합  \
0  2.0  3.0  6.0  9.0  9.0  1.0  6.0  9.0  90.0   
1  9.0  1.0  1.0  7.0  3.0  1.0  2.0  3.0  54.0   
2  7.0  7.0  0.0  3.0  8.0  7.0  6.0  6.0  88.0   
3  3.0  5.0  3.0  7.0  9.0  7.0  6.0  0.0  80.0   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN   

                                                 열의합  
0                                                NaN  
1                                                NaN  
2                                                NaN  
3                                                NaN  
4  0       21
1       16
2       10
3       26
4 ...

In [159]:
df_score1 = pd.DataFrame({
    "반":["A", "A", "B", "A", "B", "B", "B", "A", "B", "A"],
    "번호" : [1, 2, 1, 3, 2, 3, 4, 4, 5, 5],
    "국어" : [79, 67, 88, 68, 92, 54, 67, 88, 97, 85],
    "영어" : [55, 77, 44, 67, 86, 45, 78, 58, 90, 67],
    "수학" : [57, 45, 76, 68, 89, 67, 99, 78, 89, 90]
})
df_score1

반  번호  국어  영어  수학
0  A   1  79  55  57
1  A   2  67  77  45
2  B   1  88  44  76
3  A   3  68  67  68
4  B   2  92  86  89
5  B   3  54  45  67
6  B   4  67  78  99
7  A   4  88  58  78
8  B   5  97  90  89
9  A   5  85  67  90

In [163]:
df1= df_score1.set_index(['반','번호'])
df1

국어  영어  수학
반 번호            
A 1   79  55  57
  2   67  77  45
B 1   88  44  76
A 3   68  67  68
B 2   92  86  89
  3   54  45  67
  4   67  78  99
A 4   88  58  78
B 5   97  90  89
A 5   85  67  90

In [171]:
df1['평균']= df1[:].mean(axis=1)
df1

국어  영어  수학         평균
반 번호                       
A 1   79  55  57  63.666667
  2   67  77  45  63.000000
B 1   88  44  76  69.333333
A 3   68  67  68  67.666667
B 2   92  86  89  89.000000
  3   54  45  67  55.333333
  4   67  78  99  81.333333
A 4   88  58  78  74.666667
B 5   97  90  89  92.000000
A 5   85  67  90  80.666667

In [213]:
df2= df1.unstack(['반'])
df2

국어      영어      수학             평균           
반    A   B   A   B   A   B          A          B
번호                                              
1   79  88  55  44  57  76  63.666667  69.333333
2   67  92  77  86  45  89  63.000000  89.000000
3   68  54  67  45  68  67  67.666667  55.333333
4   88  67  58  78  78  99  74.666667  81.333333
5   85  97  67  90  90  89  80.666667  92.000000

In [212]:
df2.loc['평균']= df2.mean(axis=0)
df2

국어          영어          수학      
반      A     B     A     B     A     B
번호                                    
1   79.0  88.0  55.0  44.0  57.0  76.0
2   67.0  92.0  77.0  86.0  45.0  89.0
3   68.0  54.0  67.0  45.0  68.0  67.0
4   88.0  67.0  58.0  78.0  78.0  99.0
5   85.0  97.0  67.0  90.0  90.0  89.0
평균  77.4  79.6  64.8  68.6  67.6  84.0

In [176]:
df = pd.DataFrame({
    'city': ['부산', '부산', '부산', '부산', '서울', '서울', '서울'],
    'fruits': ['apple', 'orange', 'banana', 'banana', 'apple', 'apple', 'banana'],
    'price': [100, 200, 250, 300, 150, 200, 400],
    'quantity': [1, 2, 3, 4, 5, 6, 7]
})
df

city  fruits  price  quantity
0   부산   apple    100         1
1   부산  orange    200         2
2   부산  banana    250         3
3   부산  banana    300         4
4   서울   apple    150         5
5   서울   apple    200         6
6   서울  banana    400         7

In [178]:
df.groupby(['city','fruits']).mean()

price  quantity
city fruits                 
부산   apple   100.0       1.0
     banana  275.0       3.5
     orange  200.0       2.0
서울   apple   175.0       5.5
     banana  400.0       7.0

In [179]:
print(df.groupby(['fruits']).mean())
print(df.groupby(['fruits']).mean())

             price  quantity
fruits                      
apple   150.000000  4.000000
banana  316.666667  4.666667
orange  200.000000  2.000000
             price  quantity
fruits                      
apple   150.000000  4.000000
banana  316.666667  4.666667
orange  200.000000  2.000000


In [184]:
df.groupby(['fruits']).mean().reset_index()

fruits       price  quantity
0   apple  150.000000  4.000000
1  banana  316.666667  4.666667
2  orange  200.000000  2.000000

In [183]:
df.groupby(['city']).sum()

price  quantity
city                 
부산      850        10
서울      750        18

In [ ]:
df.pivot_table()

In [216]:
df= pd.DataFrame(data={'이름':['x'],'주소':['x']})
while True:
    a= input('''
    ----------------------------
    1. 친구 리스트 출력
    2. 친구 추가
    3. 친구 삭제
    9. 종료
    ''')
    if a=='1':
        print(df)
    
    if a=='2':
        lt=[]
        name= input('이름 입력:')
        addr= input('주소 입력:')
        df.loc[len(df)]=[name, addr]
        
    if a=='3':
        idx= int(input('삭제할 인덱스 입력:'))
        df.drop(idx, axis=0, inplace=True)
        
    if a=='9':
        break


    ----------------------------
    1. 친구 리스트 출력
    2. 친구 추가
    3. 친구 삭제
    9. 종료
    2
이름 입력:q
주소 입력:q

    ----------------------------
    1. 친구 리스트 출력
    2. 친구 추가
    3. 친구 삭제
    9. 종료
    1
  이름 주소
0  x  x
1  q  q

    ----------------------------
    1. 친구 리스트 출력
    2. 친구 추가
    3. 친구 삭제
    9. 종료
    3
삭제할 인덱스 입력:1

    ----------------------------
    1. 친구 리스트 출력
    2. 친구 추가
    3. 친구 삭제
    9. 종료
    1
  이름 주소
0  x  x

    ----------------------------
    1. 친구 리스트 출력
    2. 친구 추가
    3. 친구 삭제
    9. 종료
    9


In [215]:
df= pd.DataFrame(data={'이름':['xt'],'주소':['xy']})
df

이름  주소
0  xt  xy

In [200]:
df.loc[1]=[2,3]

In [202]:
len(df)

2

In [203]:
df

이름 주소
0  x  x
1  2  3